#!/system/bin/sh

case $1 in
ro)
    echo "Enabling read-only access to /system"
    /system/xbin/mount -o remount,ro /dev/block/mmcblk0p8 /system
  ;;
rw)
  echo "Enabling read/write access to /system"
  /system/xbin/mount -o remount,rw /dev/block/mmcblk0p8 /system
  ;;
*)
    echo "Invalid or no input. Try: 'remount rw' or 'remount ro'"
  ;;
esac
